spring: 
  profiles: 
    active: dev

---
server: 
  port: 8001

#spring配置
spring: 
  profiles: dev
  application: 
    name: microservice-dept-server
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/microservicecloud_db_01
    username: root
    password: 123456

#mybatis配置
mybatis: 
  type-aliases-package: com.ultrapower.springcloud.entities #实体类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml #mapper映射文件位置

#Eureka客户端注册进Eureka服务列表内
eureka: 
  client: 
    service-url: 
      defaultZone: http://eurekalocalhost:7001/eureka/
  instance:
    instance-id: dept-provider-8001
    prefer-ip-address: true #访问路径可以显示IP地址
    
#构建info详细信息
info: 
  app.name: microService_dept_provider
  company.name: www.ultrapower.com
  build.artifactId: $project.artifactId$
  build.version:  $project.version$

---
server: 
  port: 8001

#spring配置
spring: 
  profiles: test
  application: 
    name: microservice-dept-server
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/microservicecloud_db_02
    username: root
    password: 123456

#mybatis配置
mybatis: 
  type-aliases-package: com.ultrapower.springcloud.entities #实体类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml #mapper映射文件位置

#Eureka客户端注册进Eureka服务列表内
eureka: 
  client: 
    service-url: 
      defaultZone: http://eurekalocalhost:7001/eureka/
  instance:
    instance-id: dept-provider-8001
    prefer-ip-address: true #访问路径可以显示IP地址
    
#构建info详细信息
info: 
  app.name: microService_dept_provider
  company.name: www.ultrapower.com
  build.artifactId: $project.artifactId$
  build.version:  $project.version$