spring:  
  profiles:  
    active: dev
---
server:  
  port: 7001

spring: 
  profiles: dev
  application:  
    name: microservice-config-eureka-server

eureka: 
  instance: 
    hostname: eureka7001.com
  client: 
    register-with-eureka: false #自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
---
server: 
  port: 7001

spring: 
  profiles: test
  application: 
    name: microservice-config-eureka-server

eureka: 
  instance: 
    hostname: eureka7001.com
  client: 
    register-with-eureka: false #自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/